### ISSUE TITLE
App crashing when calculating any route

### ISSUE THREAD

**Issue by Mavyre** [L-Belluomini/OTN#4]
Hello,

I just tried out your plugin. I generated succesfully the routing graph for my country.
However, when trying any route from ATAK, the app entirely closes.

From the crashlog (attached to this issue), it seems that ATAK goes Out of Memory. The phone has 12GB memory though.

Any idea how to fix that?

Here are the logs: [logs_MANTA_2022-03-13T00-44-33Z.zip](https://github.com/L-Belluomini/OTN/files/8238777/logs_MANTA_2022-03-13T00-44-33Z.zip)

**Comment by L-Belluomini** [comment]
Hi, you found the right problem OTN goes out of memory, this happens because the android OS limits the amount of ram single app can allocate to around 1 Gb. form other test the france graph is to big to fit in said limit. as a work around try using single provinces and not the whole country. newer version of OTN and OTNc should help manage the issue.

**Comment by Mavyre** [comment]
Hey, thanks about the insight. I had no clue about the maximum Java Heap memory in Android. When using OTNCompanion, I had to raise it to 24Gb (using -Xmx). I searched a way to do it on mobile, but didn't find a way yet.

I'll try to reduce dig in the province I'm trying to make it work on and keep you updated!

**Comment by Mavyre** [comment]
Hey,

I tried out with a sub file from France. Works like a charm!

I'm keeping the issue open, so we can track down the crash.

Thank you for the help!

**Comment by L-Belluomini** [comment]
new version manages both in memory and on file graphs, which solves the issue.
